name: Build and test on Jetstream2

on:
  workflow_dispatch: # Trigger manually from github

jobs:
  terraform:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up terraform
      uses: hashicorp/setup-terraform@v3

    - name: Set environment variables
      run: |
        echo "OS_AUTH_TYPE=v3applicationcredential" >> $GITHUB_ENV
        echo "OS_AUTH_URL=https://js2.jetstream-cloud.org:5000/v3/" >> $GITHUB_ENV
        echo "OS_IDENTITY_API_VERSION=3" >> $GITHUB_ENV
        echo "OS_REGION_NAME=IU" >> $GITHUB_ENV
        echo "OS_INTERFACE=public" >> $GITHUB_ENV
        echo "OS_APPLICATION_CREDENTIAL_ID=${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}" >> $GITHUB_ENV
        echo "OS_APPLICATION_CREDENTIAL_SECRET=${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}" >> $GITHUB_ENV

    - name: Terraform init
      run: terraform init

    - name: Terraform validate
      run: terraform validate

    - name: Terraform apply
      working-directory: terraform
      env:
        TF_VAR_jetstream_private_key: ${{ secrets.JETSTREAM_SSH_KEY }}
        TF_VAR_mpi_private_key: ${{ secrets.MPI_KEY }}
      run: terraform apply -auto-approve

    - name: Add SSH key to runner
      run: |
        echo "${{ secrets.JETSTREAM_SSH_KEY }}" > ~/jetstream_key
        chmod 600 ~/jetstream_key

    - name: Get IPs and set up host file
      run: |
        sleep 60 # Wait for instances to start

        PUBLIC_IPS_JSON=$(terraform output -json public_ips)
        PRIVATE_IPS_JSON=$(terraform output -json private_ips)

        IP1=$(echo "$PUBLIC_IPS_JSON" | jq -r '.[0]')
        echo "IP1=$IP1" >> $GITHUB_ENV
        echo "Using IP1: $IP1"

        echo "$PRIVATE_IPS_JSON" | jq -r '.[] + " slots=2"' > hosts.txt
        scp -o StrictHostKeyChecking=no -i ~/jetstream_key hosts.txt ubuntu@$IP1:~/hosts.txt

        echo "${{ secrets.MPI_KEY }}" > mpi_key
        chmod 600 mpi_key
        
        mapfile -t IPS < <(echo "$PUBLIC_IPS_JSON" | jq -r '.[]')

        for IP in "${IPS[@]}"; do
          echo "Copying mpi_keys to $IP"
          scp -o StrictHostKeyChecking=no -i ~/jetstream_key mpi_key.pub ubuntu@"$IP":~/mpi_key.pub
          scp -o StrictHostKeyChecking=no -i ~/jetstream_key mpi_key ubuntu@"$IP":~/mpi_key
        done

    - name: SSH and build on instance
      env:
        IP1: ${{ env.IP1 }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/jetstream_key ubuntu@$IP1 <<'EOF'
          cd /changa-network/cicd
          rm -rf changa charm utility
          git clone https://github.com/charmplusplus/charm.git
          cd charm
          ./build ChaNGa mpi-linux-x86_64 smp --with-production -j4
          cd ..
          git clone -b cicd https://github.com/spencerw/changa.git changa
          git clone https://github.com/N-BodyShop/utility
          cd changa
          ./configure
          make -j4
        EOF

    - name: Run tests
      timeout-minutes: 30
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/jetstream_key ubuntu@$IP1 <<'EOF'
          cd /changa-network/cicd/changa/teststep
          mpirun -np 2 --hostfile ~/hosts.txt --mca btl_tcp_if_include enp1s0 --mca plm_rsh_args "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/mpi_key" ../ChaNGa.smp ++ppn 2 +pemap 0-1 +commap 2 +setcpuaffinity test_pg.param
          make testenergy
        EOF

    - name: Terraform destroy
      if: always() # Clean up even if we have failures
      run: terraform destroy -auto-approve
